# Generated by Django 6.0.4 on 2026-04-16 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del solicitante')),
                ('documento_identidad', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El documento de identidad debe contener solo caracteres alfanuméricos.', regex='^[A-Za-z0-9]+$')], verbose_name='Documento de identidad')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('tipo_solicitud', models.CharField(choices=[('ACADEMICA', 'Académica'), ('ADMINISTRATIVA', 'Administrativa'), ('TECNICA', 'Técnica'), ('OTRA', 'Otra')], max_length=20, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de la solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/adjuntos/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud', '-created_at'],
            },
        ),
    ]
