# Generated by Django 6.0.3 on 2026-04-16 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del solicitante')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese solo dígitos', regex='^[0-9]+$')], verbose_name='Teléfono de contacto')),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha', models.DateField(verbose_name='Fecha de la solicitud')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/', verbose_name='Archivo adjunto')),
            ],
        ),
    ]
