# Generated by Django 6.0.4 on 2026-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono de contacto'),
        ),
    ]
